# Generated by Django 4.2.7 on 2023-11-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsocial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestainicial',
            name='persona_cobra_chequera',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='persona_cobra_chequera'),
        ),
    ]
