# Generated by Django 4.2.7 on 2023-11-22 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsocial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composicionfamiliar',
            old_name='nombre',
            new_name='nombre_f',
        ),
    ]
