# Generated by Django 4.2.7 on 2023-11-18 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsocial', '0002_encuestainicial_persona_cobra_chequera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayudatecnica',
            name='at_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_paciente', to='tsocial.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='composicionfamiliar',
            name='cf_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cf_paciente', to='tsocial.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='controlpase',
            name='cp_familiar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp_familiar', to='tsocial.composicionfamiliar', verbose_name='Familiar'),
        ),
        migrations.AlterField(
            model_name='controlpase',
            name='cp_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp_paciente', to='tsocial.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='discapacidad',
            name='disc_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disc_paciente', to='tsocial.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='encuestainicial',
            name='enc_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enc_paciente', to='tsocial.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='trabajodiario',
            name='td_familiar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='td_familiar', to='tsocial.composicionfamiliar', verbose_name='Familiar'),
        ),
        migrations.AlterField(
            model_name='trabajodiario',
            name='td_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='td_paciente', to='tsocial.paciente', verbose_name='Paciente'),
        ),
    ]
