# Generated by Django 4.2.7 on 2023-11-15 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tsocial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defectologia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('auditivo', models.BooleanField(default=False, verbose_name='Auditivo')),
                ('visual', models.BooleanField(default=False, verbose_name='Visual')),
                ('ecv', models.BooleanField(default=False, verbose_name='ECV')),
                ('fisicomotora', models.BooleanField(default=False, verbose_name='Físico motora')),
                ('retrazomental', models.CharField(max_length=15, verbose_name='Retrazo mental')),
                ('trastornolenguaje', models.CharField(max_length=15, verbose_name='Trastorno del lenguaje')),
                ('trastornopensamiento', models.CharField(max_length=15, verbose_name='Trastorno del pensamiento')),
                ('d_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_paciente', to='tsocial.paciente', verbose_name='Defectología')),
            ],
            options={
                'verbose_name': 'Defectología',
                'verbose_name_plural': 'Defectologías',
                'db_table': 'defectologia',
            },
        ),
        migrations.CreateModel(
            name='Cognitivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('esquizofrenia', models.BooleanField(default=False, verbose_name='Esquizofrenia')),
                ('fumador', models.BooleanField(default=False, verbose_name='Fumador')),
                ('alcoholico', models.BooleanField(default=False, verbose_name='Alcohólico')),
                ('demencia', models.BooleanField(default=False, verbose_name='Demencia')),
                ('parkinson', models.BooleanField(default=False, verbose_name='Parkinson')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('c_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_paciente', to='tsocial.paciente', verbose_name='Cognitivo')),
            ],
            options={
                'verbose_name': 'Cognitivo',
                'verbose_name_plural': 'Cognitivos',
                'db_table': 'cognitivo',
            },
        ),
        migrations.CreateModel(
            name='Afectiva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('depresion', models.BooleanField(default=False, verbose_name='Depresión')),
                ('anciedad', models.BooleanField(default=False, verbose_name='Anciedad')),
                ('intentosuicida', models.BooleanField(default=False, verbose_name='Intento suicida')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('a_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_paciente', to='tsocial.paciente', verbose_name='Afectiva')),
            ],
            options={
                'verbose_name': 'Afectiva',
                'verbose_name_plural': 'Afectivas',
                'db_table': 'afectiva',
            },
        ),
    ]
