# Generated by Django 4.2.7 on 2023-11-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomdepsevera',
            options={'verbose_name': 'Nomenclador Depresión Severa', 'verbose_name_plural': 'Nomencladores Depresiones Severas'},
        ),
        migrations.AddField(
            model_name='defectologia',
            name='resultado',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Evaluación Mental'),
        ),
    ]
