# Generated by Django 4.2.7 on 2023-11-20 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsocial', '0003_alter_ayudatecnica_at_paciente_and_more'),
        ('psicologia', '0002_enars_resultado_saludmental_yasevage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectologia',
            name='d_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_paciente', to='tsocial.paciente', verbose_name='Paciente'),
        ),
    ]
