# Generated by Django 4.2.7 on 2023-11-17 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsocial', '0002_encuestainicial_persona_cobra_chequera'),
        ('asistmedica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('evaluacion', models.CharField(max_length=10, verbose_name='Evaluación')),
                ('puntuacion', models.PositiveSmallIntegerField(verbose_name='Puntuación')),
            ],
            options={
                'verbose_name': 'Nomenclador Actividad',
                'verbose_name_plural': 'Nomencladores Actividades',
                'db_table': 'nomactividad',
            },
        ),
        migrations.CreateModel(
            name='NomEstadoGeneral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('evaluacion', models.CharField(max_length=10, verbose_name='Evaluación')),
                ('puntuacion', models.PositiveSmallIntegerField(verbose_name='Puntuación')),
            ],
            options={
                'verbose_name': 'Nomenclador Estado General',
                'verbose_name_plural': 'Nomencladores Estados Generales',
                'db_table': 'nomestadogeneral',
            },
        ),
        migrations.CreateModel(
            name='NomEstadoMental',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('evaluacion', models.CharField(max_length=10, verbose_name='Evaluación')),
                ('puntuacion', models.PositiveSmallIntegerField(verbose_name='Puntuación')),
            ],
            options={
                'verbose_name': 'Nomenclador Estado Mental',
                'verbose_name_plural': 'Nomencladores Estados Mental',
                'db_table': 'nomestadoMental',
            },
        ),
        migrations.CreateModel(
            name='NomIncontinencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('evaluacion', models.CharField(max_length=10, verbose_name='Evaluación')),
                ('puntuacion', models.PositiveSmallIntegerField(verbose_name='Puntuación')),
            ],
            options={
                'verbose_name': 'Nomenclador Incontinencia',
                'verbose_name_plural': 'Nomencladores Incontinencia',
                'db_table': 'nomincontinencia',
            },
        ),
        migrations.CreateModel(
            name='NomMovilidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('evaluacion', models.CharField(max_length=10, verbose_name='Evaluación')),
                ('puntuacion', models.PositiveSmallIntegerField(verbose_name='Puntuación')),
            ],
            options={
                'verbose_name': 'Nomenclador Movilidad',
                'verbose_name_plural': 'Nomencladores Movilidad',
                'db_table': 'nommovilidad',
            },
        ),
        migrations.AddField(
            model_name='indicevalue',
            name='resultado',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='indicevalue',
            name='estado_general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_general', to='tsocial.paciente', verbose_name='Estado General'),
        ),
        migrations.AlterField(
            model_name='indicevalue',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad', to='asistmedica.nomactividad', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='indicevalue',
            name='estado_mental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_mental', to='asistmedica.nomestadogeneral', verbose_name='Estado Mental'),
        ),
        migrations.AlterField(
            model_name='indicevalue',
            name='incontinencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incontinencia', to='asistmedica.nomincontinencia', verbose_name='Incontinencia'),
        ),
        migrations.AlterField(
            model_name='indicevalue',
            name='movilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movilidad', to='asistmedica.nommovilidad', verbose_name='Movilidad'),
        ),
    ]
