# Generated by Django 4.2.7 on 2023-11-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistmedica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sindrome',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
