# Generated by Django 4.2.7 on 2023-11-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistmedica', '0003_alter_nomestadomental_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomestadomental',
            name='evaluacion',
            field=models.CharField(max_length=10, verbose_name='Evaluación'),
        ),
        migrations.AlterField(
            model_name='nomincontinencia',
            name='evaluacion',
            field=models.CharField(max_length=20, verbose_name='Evaluación'),
        ),
    ]
