# Generated by Django 4.2.7 on 2023-11-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistmedica', '0007_remove_datoenfermeria_imc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datoenfermeria',
            name='diagnostico_angiologia',
        ),
        migrations.RemoveField(
            model_name='datoenfermeria',
            name='diagnostico_cardiologia',
        ),
        migrations.RemoveField(
            model_name='datoenfermeria',
            name='diagnostico_cirugia',
        ),
        migrations.RemoveField(
            model_name='datoenfermeria',
            name='diagnostico_dermatologia',
        ),
        migrations.RemoveField(
            model_name='datoenfermeria',
            name='diagnostico_fisiatria',
        ),
        migrations.RemoveField(
            model_name='datoenfermeria',
            name='diagnostico_geriatria',
        ),
        migrations.RemoveField(
            model_name='datoenfermeria',
            name='diagnostico_oncologia',
        ),
        migrations.RemoveField(
            model_name='datoenfermeria',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='datoenfermeria',
            name='fecha_an',
        ),
        migrations.RemoveField(
            model_name='datoenfermeria',
            name='fecha_car',
        ),
        migrations.RemoveField(
            model_name='datoenfermeria',
            name='fecha_cir',
        ),
        migrations.RemoveField(
            model_name='datoenfermeria',
            name='fecha_der',
        ),
        migrations.RemoveField(
            model_name='datoenfermeria',
            name='fecha_fi',
        ),
        migrations.RemoveField(
            model_name='datoenfermeria',
            name='fecha_ge',
        ),
        migrations.RemoveField(
            model_name='datoenfermeria',
            name='fecha_on',
        ),
        migrations.RemoveField(
            model_name='datoenfermeria',
            name='otros_diagnosticos',
        ),
        migrations.AddField(
            model_name='datoenfermeria',
            name='resumen',
            field=models.TextField(blank=True, null=True, verbose_name='Resumen de consultas externas'),
        ),
    ]
