# Generated by Django 4.2.7 on 2023-11-20 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsocial', '0003_alter_ayudatecnica_at_paciente_and_more'),
        ('asistmedica', '0008_remove_datoenfermeria_diagnostico_angiologia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mnt',
            name='fecha_mnt',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='katsvalue',
            name='kat_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kat_paciente', to='tsocial.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='lawtonvalue',
            name='law_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='law_paciente', to='tsocial.paciente', verbose_name='Paciente'),
        ),
    ]
