# Generated by Django 4.2.7 on 2023-11-20 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
        ('tsocial', '0003_alter_ayudatecnica_at_paciente_and_more'),
        ('asistmedica', '0009_mnt_fecha_mnt_alter_katsvalue_kat_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpedido',
            name='sp_indic',
        ),
        migrations.AlterField(
            model_name='indicacion',
            name='indic_datoenf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indic_datoenf', to='asistmedica.datoenfermeria', verbose_name='IMC'),
        ),
        migrations.AlterField(
            model_name='indicacion',
            name='indic_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indic_paciente', to='tsocial.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='indicacion',
            name='indic_termo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indic_termo', to='asistmedica.termometria', verbose_name='Temperatura'),
        ),
        migrations.AlterField(
            model_name='solicitudpedido',
            name='sp_disp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp_disp', to='farmacia.dispensacion', verbose_name='Dispensación'),
        ),
    ]
