# Generated by Django 4.2.7 on 2023-11-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('codigo', models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='codigo')),
                ('nombre_inst', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lugar', models.CharField(max_length=50, verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Centro',
                'verbose_name_plural': 'Centros',
                'db_table': 'centro',
            },
        ),
    ]
